server:
  port: 9001
spring:
  datasource:
    #MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.194.131:3306/energy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: 123456
logging:
  level:
    com.dao: DEBUG
mybatis:
  mapper-locations: classpath:mappers/*.xml